### PR TITLE
Update gems

### PR DESCRIPTION
**Pull request by stefano-sarioli**
We decided to update all the gems for the release of the new Solidus version (2.11).

The only notable change is that the front end started removed the header's partial. To be better equipped for future changes, we decided to use `deface` to append our guided tour partial to the header.

I've also fixed a broken link with an icon inside the CSS.

Let me know what do you think and if this looks good to you.

### CODE REVIEW

**Review by kennyadsl — APPROVED** [review]

**Comment by kennyadsl** [comment]
@stefano-sarioli looks good but there's a conflict, can you please take a look?

**Review by seand7565 — CHANGES_REQUESTED** [review]
Hey, thanks @stefano-sarioli ! This is fantastic work!

One question - this PR adds two tables, action_mailbox_inbound_emails and action_text_rich_texts.

The way the demo scopes it's data is based on the existence of a `sample_indicator_id` field on every table. [See here](https://github.com/nebulab/solidus-demo/blob/master/db/migrate/20200529174800_add_sample_indicator_id_to_everything.rb). 

I am not sure exactly how those tables are used, but it's probably best to keep with that convention to avoid any problems. 

Also I don't think this is explained anywhere - I'll create a PR shortly to add this to the README, since it's important to the functionality of the demo.

**Comment by stefano-sarioli** [comment]
Thank you for the review 🙏 . 

I've added the missing field to the database.
I also had to update the deface integration to make it work with add Google Tag Manager.

**Comment by seand7565** [comment]
Looks great, works good on my machine too. Just need to re-run the migrations to update the schema. Thanks @stefano-sarioli !

**Review by seand7565 — APPROVED** [review]
Great work, thanks!

**Pull request merged**
